### ISSUE TITLE
Compilation fails on master and development

### ISSUE THREAD

**Issue by yourheropaul** [Joystream/substrate-node-joystream#81]
`cargo run` (more specifically, `cargo <run|build> [--release]`, yields:
 
```
   Compiling joystream-node v1.0.0 (/home/paul/Projects/jsgenesis/substrate-node-joystream)
error[E0063]: missing field `forum` in initializer of `joystream_node_runtime::GenesisConfig`
   --> src/chain_spec.rs:192:5
    |
192 |     GenesisConfig {
    |     ^^^^^^^^^^^^^ missing `forum`

error[E0063]: missing field `forum` in initializer of `joystream_node_runtime::GenesisConfig`
   --> src/chain_spec.rs:294:5
    |
294 |     GenesisConfig {
    |     ^^^^^^^^^^^^^ missing `forum`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0063`.
error: Could not compile `joystream-node`.
```

This seems to be some sort of desync issue with the upstream runtime. Cargo updates the lockfile version from `5.1.0` to `5.4.0` on build or run execution.

**Comment by mnaamani** [comment]
Since we only planned a runtime upgrade for last testnet we didn't update the node repo to build with latest 5.4.0 runtime. This will be a task for Rome release.

**Comment by ksinghf** [comment]
@mnaamani so for the moment what is the best way to build and run a dev environment? Is there a tag or a branch that could work for now?

**Comment by mnaamani** [comment]
> @mnaamani so for the moment what is the best way to build and run a dev environment? Is there a tag or a branch that could work for now?

The latest development environment now would be to build node from:
https://github.com/Joystream/substrate-node-joystream/pull/85

And the corresponding front-end (pioneer) from https://github.com/Joystream/apps/pull/240

**Comment by mnaamani** [comment]
Update. To build the current testnet version of the node you have to checkout `v5.3.0` of the runtime. So if you followed the step in the readme you can take following steps starting in the `substrate-node-joystream` folder:

```bash
cd substrate-runtime-joystream
git fetch --tags
git checkout v5.3.0
cd ../
./build-runtime.sh
cargo build --release
```
